server:
  port: 8080
  forward-headers-strategy: framework

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    displayRequestDuration: true
    syntaxHighlight:
      activated: true
  show-actuator: false
  packages-to-scan: com.jgonzal.retail.adapters.input.rest
  paths-to-match: /customers/**
  use-management-port: false
  cache:
    disabled: true